name: Bot Approve PR

on:
  issue_comment:
    types: [created]          # 新しいコメントが付いたとき

permissions:
  pull-requests: write        # ★ Approve には必須

jobs:
  auto-approve:
    # コメントが PR に付いたもの かつ 本文が '/bot-approve' の場合のみ実行
    if: |
      github.event.issue.pull_request &&
      github.event.comment.body == '/bot-approve'
    runs-on: ubuntu-latest

    steps:
      # 1) GitHub CLI をインストール（Ubuntu 24.04 は未インストール）
      - name: Install GitHub CLI
        run: |
          sudo apt-get update -y
          sudo apt-get install -y gh

      # 2) Bot の PAT を GH_TOKEN として渡し、Approve 実行
      - name: Approve this PR as Bot
        env:
          GH_TOKEN: ${{ secrets.CLASSIC_BOT_PAT }}
        run: |
          PR_URL=${{ github.event.issue.pull_request.html_url }}
          echo "Approving PR: $PR_URL"
          gh pr review "$PR_URL" --approve
