name: Bot Approve PR

on:
  issue_comment:
    types: [created]        # 新しいコメントが付いたとき

# ↓ Approve には “pull-requests: write” 権限が必須
permissions:
  pull-requests: write

jobs:
  auto-approve:
    if: |
      github.event.issue.pull_request &&
      contains(github.event.comment.body, '/bot-approve')
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-gh@v2
      - name: Approve this PR
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_URL:  ${{ github.event.issue.pull_request.html_url }}
        run: gh pr review "$PR_URL" --approve
